<?php
/** All quotations from all parties, with filters — SRS 5.4. */

require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/layout.php';
require_once __DIR__ . '/../includes/admin_nav.php';

require_admin();

$filterParty  = (int) get_str('party', '0');
$filterNo     = get_str('no');
$filterFrom   = get_str('from');
$filterTo     = get_str('to');

$where = '1=1';
$params = [];

if ($filterParty > 0) {
    $where .= ' AND q.party_id = ?';
    $params[] = $filterParty;
}
if ($filterNo !== '') {
    $where .= ' AND q.quotation_no LIKE ?';
    $params[] = '%' . $filterNo . '%';
}
if ($filterFrom !== '') {
    $where .= ' AND q.created_at >= ?';
    $params[] = $filterFrom . ' 00:00:00';
}
if ($filterTo !== '') {
    $where .= ' AND q.created_at <= ?';
    $params[] = $filterTo . ' 23:59:59';
}

$quotations = db_all(
    "SELECT q.*, p.company_name, p.party_code
       FROM quotations q
       JOIN parties p ON p.id = q.party_id
      WHERE $where
      ORDER BY q.created_at DESC, q.id DESC
      LIMIT 300",
    $params
);

$parties = db_all('SELECT id, company_name, party_code FROM parties ORDER BY company_name');

layout_header('Quotations', 'admin', admin_nav(), 'quotations');
?>

<div class="page-head">
  <div>
    <h1>Quotations</h1>
    <p>Every quotation generated by every party.</p>
  </div>
</div>

<div class="card">
  <form method="get" class="filter-form">
    <div class="field">
      <label for="party">Party</label>
      <select id="party" name="party">
        <option value="">All parties</option>
        <?php foreach ($parties as $party): ?>
          <option value="<?= (int) $party['id'] ?>" <?= $filterParty === (int) $party['id'] ? 'selected' : '' ?>>
            <?= e($party['company_name']) ?> (<?= e($party['party_code']) ?>)
          </option>
        <?php endforeach; ?>
      </select>
    </div>
    <div class="field">
      <label for="no">Quotation no.</label>
      <input type="text" id="no" name="no" value="<?= e($filterNo) ?>" placeholder="CG-Q-0001">
    </div>
    <div class="field">
      <label for="from">From</label>
      <input type="date" id="from" name="from" value="<?= e($filterFrom) ?>">
    </div>
    <div class="field">
      <label for="to">To</label>
      <input type="date" id="to" name="to" value="<?= e($filterTo) ?>">
    </div>
    <button type="submit" class="btn btn-primary">Filter</button>
    <a class="btn btn-outline" href="<?= e(url('admin/quotations.php')) ?>">Clear</a>
  </form>
</div>

<div class="card">
  <?php if (!$quotations): ?>
    <p class="empty-state">No quotations match these filters.</p>
  <?php else: ?>
    <div class="table-wrap">
      <table class="data">
        <thead>
          <tr><th>Quotation No.</th><th>Party</th><th>Date</th><th>Items</th><th>Pieces</th><th></th></tr>
        </thead>
        <tbody>
          <?php foreach ($quotations as $q): ?>
            <tr>
              <td><strong><?= e($q['quotation_no']) ?></strong></td>
              <td><?= e($q['company_name']) ?><br><span class="hint"><?= e($q['party_code']) ?></span></td>
              <td><?= e(date('d M Y, H:i', strtotime((string) $q['created_at']))) ?></td>
              <td><?= (int) $q['item_count'] ?></td>
              <td><?= (int) $q['total_qty'] ?></td>
              <td class="table-actions">
                <a class="btn btn-outline btn-sm" href="<?= e(url('admin/quotation-view.php?id=' . (int) $q['id'])) ?>">View</a>
                <a class="btn btn-primary btn-sm" href="<?= e(url('admin/quotation-pdf.php?id=' . (int) $q['id'])) ?>">PDF</a>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  <?php endif; ?>
</div>

<?php layout_footer(); ?>
